config/routes.rb
Rails.application.routes.draw do
  resources :pessoas

  resources :aniversariantes, only: :index

  root to: 'pessoas#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
  validates_presence_of :nome, :data_nascimento

  def self.aniversariantes
    aniversariantes = {}
    
    proximos_aniversariantes.each do |pessoa|
      next if pessoa.data_nascimento.blank?
      next if Date.parse("#{pessoa.data_nascimento.day}/#{pessoa.data_nascimento.month}/#{Date.today.year}") < Date.today

      data = I18n.l(Date.parse("1/#{pessoa.data_nascimento.month}/#{Date.today.year}"), format: :short2)
      aniversariantes[data] ||= []
      aniversariantes[data] << pessoa
    end

    aniversariantes
  end

  private

  def self.proximos_aniversariantes
    Pessoa.all.order('extract(MONTH from data_nascimento), extract(DAY from data_nascimento)')
  end
end

app/controllers/aniversariantes_controller.rb
class AniversariantesController < ApplicationController
  def index
    @aniversariantes = Pessoa.aniversariantes
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: [:show, :edit, :update, :destroy]

  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.all.order('nome')
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully created.' }
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.html { render :new }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoas/1
  # PATCH/PUT /pessoas/1.json
  def update
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully updated.' }
        format.json { render :show, status: :ok, location: @pessoa }
      else
        format.html { render :edit }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa.destroy
    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: 'Pessoa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pessoa_params
      params.require(:pessoa).permit(:nome, :tipo, :endereco, :data_nascimento, :telefone, :cep, :bairro, :observacoes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/views/aniversariantes/index.html.erb
<h1>Aniversariantes</h1>

<% @aniversariantes.each do |mes_ano, pessoas| %>
  <div class="card">
    <div class="card-header text-center">
      <b><%= mes_ano %></b>
    </div>
    <ul class="list-group list-group-flush">
      <% pessoas.each do |pessoa| %>
        <li class="list-group-item">
          <p><b><%= pessoa.nome %></b></p>
          <p class="card-text"><small class="text-muted"><%= l(pessoa.data_nascimento, format: :short)%></small></p>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>davizinho</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href=<%= root_path %>>Davizinho</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href=<%= pessoas_path %>>Pessoas <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href=<%= aniversariantes_path %>>Aniversariantes</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container-fluid" style="margin-top: 65px;">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pessoas/_form.html.erb
<%= form_for @pessoa, :html => { :class => "form-horizontal pessoa" } do |f| %>

  <% if @pessoa.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title">Ocorreram <%= pluralize(@pessoa.errors.count, "problema", "problemas") %>:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @pessoa.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-row">
    <div class="form-group col-md-4" style="margin-top: 35px;">
      <div class="form-check-inline">
        <input class="form-check-input" type="radio" name="pessoa[tipo]" id="tipo1" value="davizinho" checked>
        <label class="form-check-label" for="tipo1">
          Davizinho
        </label>
      </div>
      <div class="form-check-inline">
        <input class="form-check-input" type="radio" name="pessoa[tipo]" id="tipo2" value="outros">
        <label class="form-check-label" for="tipo2">
          Outros
        </label>
      </div>
      <%=f.error_span(:tipo) %>
    </div>
  </div>

  <div class="form-row">
  
    <div class="form-group col-md-8">
      <%= f.label :nome %>
      <%= f.text_field :nome, :class => 'form-control' %>
      <%=f.error_span(:nome) %>
    </div>

    <div class="form-group col-md-2">
      <%= f.label :data_nascimento %>
      <%= f.date_field :data_nascimento, :class => 'form-control' %>
      <%=f.error_span(:data_nascimento) %>
    </div>

    <div class="form-group col-md-2">
      <%= f.label :telefone %>
      <%= f.text_field :telefone, :class => 'form-control' %>
      <%=f.error_span(:telefone) %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-1">
      <%= f.label :cep %>
      <%= f.text_field :cep, :class => 'form-control' %>
      <%=f.error_span(:cep) %>
    </div>

    <div class="form-group col-md-3">
      <%= f.label :municipio %>
      <%= f.text_field :municipio, :class => 'form-control' %>
      <%=f.error_span(:municipio) %>
    </div>

    <div class="form-group col-md-4">
      <%= f.label :endereco %>
      <%= f.text_field :endereco, :class => 'form-control' %>
      <%=f.error_span(:endereco) %>
    </div>

    <div class="form-group col-md-1">
      <%= f.label :numero %>
      <%= f.text_field :numero, :class => 'form-control' %>
      <%=f.error_span(:numero) %>
    </div>

    <div class="form-group col-md-2">
      <%= f.label :bairro %>
      <%= f.text_field :bairro, :class => 'form-control' %>
      <%=f.error_span(:bairro) %>
    </div>

    <div class="form-group col-md-1">
      <%= f.label :uf %>
      <%= f.text_field :uf, :class => 'form-control' %>
      <%=f.error_span(:uf) %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-md-12">
      <%= f.label :observacoes %>
      <%= f.text_area :observacoes, :class => 'form-control' %>
      <%=f.error_span(:observacoes) %>
    </div>
  </div>

    <div class="form-group">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  pessoas_path, :class => 'btn btn-default' %>
    </div>

<% end %>

app/views/pessoas/edit.html.erb
<%- model_class = Pessoa -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pessoas/index.html.erb
<%- model_class = Pessoa -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_pessoa_path,
            :class => 'btn btn-primary' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:tipo) %></th>
      <th><%= model_class.human_attribute_name(:data_nascimento) %></th>
      <th><%= model_class.human_attribute_name(:telefone) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pessoas.each do |pessoa| %>
      <tr>
        <td><%= link_to pessoa.id, pessoa_path(pessoa) %></td>
        <td><%= pessoa.nome %></td>
        <td><%= pessoa.tipo %></td>
        <% if pessoa.data_nascimento.present? %>
          <td><%= l pessoa.data_nascimento %></td>
        <% else %>
          <td><%= pessoa.data_nascimento %></td>
        <% end %>
        <td><%= pessoa.telefone %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      pessoa_path(pessoa), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_pessoa_path(pessoa), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      pessoa_path(pessoa),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_pessoa_path,
            :class => 'btn btn-primary' %>

app/views/pessoas/new.html.erb
<%- model_class = Pessoa -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pessoas/show.html.erb
<%- model_class = Pessoa -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @pessoa.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:tipo) %>:</strong></dt>
  <dd><%= @pessoa.tipo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:endereco) %>:</strong></dt>
  <dd><%= @pessoa.endereco %></dd>
  <dt><strong><%= model_class.human_attribute_name(:data_nascimento) %>:</strong></dt>
  <dd><%= @pessoa.data_nascimento %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telefone) %>:</strong></dt>
  <dd><%= @pessoa.telefone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cep) %>:</strong></dt>
  <dd><%= @pessoa.cep %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bairro) %>:</strong></dt>
  <dd><%= @pessoa.bairro %></dd>
  <dt><strong><%= model_class.human_attribute_name(:observacoes) %>:</strong></dt>
  <dd><%= @pessoa.observacoes %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              pessoas_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_pessoa_path(@pessoa), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              pessoa_path(@pessoa),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>